global:
  scrape_interval: "30s"

remote_write:
  - url: "https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom/push"
    basic_auth:
      username: "2220727"
      password: "glc_eyJvIjoiMTMyNzUxMSIsIm4iOiJzdGFjay0xMTQ4MjQyLWFsbG95LW9wZW5zdGFjay1wbGF0Zm9ybSIsImsiOiI5eW1MODA1MzAwWXM2Qks5T0s3elZRR2EiLCJtIjp7InIiOiJwcm9kLWV1LXdlc3QtMiJ9fQ=="

scrape_configs:
  - job_name: node
    static_configs:
      - targets:
          - "10.200.0.1:9100"
          - "10.200.0.2:9100"

  - job_name: cadvisor
    static_configs:
      - targets:
          - "10.200.0.1:18080"
          - "10.200.0.2:18080"

  - job_name: prometheus
    static_configs:
      - targets:
          - "10.200.0.1:9091"

  - job_name: alertmanager
    static_configs:
      - targets:
          - "10.200.0.1:9093"

  - job_name: openstack_exporter
    static_configs:
      - targets:
          - "10.200.0.1:9198"

  - job_name: blackbox_exporter
    static_configs:
      - targets:
          - "10.200.0.1:9115"

  - job_name: memcached_exporter
    static_configs:
      - targets:
          - "10.200.0.1:9150"

  - job_name: mysqld_exporter
    static_configs:
      - targets:
          - "10.200.0.1:9104"

  - job_name: libvirt_exporter
    static_configs:
      - targets:
          - "10.200.0.2:9177"


