inputs:
  inputs:
    python-version:
      description: Python version to set up for Ansible execution
      required: false
      default: "3.11"
runs:
  using: composite
  steps:
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v8.1.0
      with:
        python-version: '3.14'

    - name: Install python dependencies
      # language=bash
      run: |
        uv sync
      shell: bash

    - name: Install ansible dependencies
      # language=bash
      run: |
        uv run ansible-galaxy collection install -r requirements.yml
      shell: bash

    - name: Configure SSH key
      uses: ./.github/actions/setup-ssh-key
      with:
        secret-name: ovh-vps-ssh-private-key

    - name: Show generated inventory
      # language=bash
      run: |
        python ansible/scripts/inventory_from_tfvars.py --list | python -m json.tool
      shell: bash
