---
- name: Run OpenStack Kolla maintenance lifecycle commands
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    openstack_kolla_target_group: ovh_dedicated_servers

  roles:
    - role: openstack
