---
- name: Reconfigure Prometheus services with Kolla-Ansible
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    openstack_kolla_target_group: ovh_dedicated_servers
    openstack_kolla_needs_network_facts: false
    openstack_kolla_commands:
      - reconfigure
    openstack_kolla_extra_args: "--tags prometheus"

  roles:
    - role: openstack
